import {
  HeartHandshake,
  Moon,
  Droplets,
  UserCheck,
  MessageCircleHeart,
  Sparkles,
  Users,
  Apple,
  Baby,
  CalendarX2,
  BandageIcon,
} from "lucide-react";

export const POLICIES_GROUP_ONE = [
  {
    icon: HeartHandshake,
    title: "Settling In",
    tagline: "Gentle Starts for Every Child",
    text: "No child at Kayo is handed over at a gate and left to cope. In the opening days, a parent stays alongside their child for an agreed stretch of time, shortening gradually as familiarity grows. Some children settle in three days, some need three weeks — the timetable belongs to the child, and our teachers adjust to it, never the reverse.",
    tone: "primary",
    size: "lg",
  },
  {
    icon: Moon,
    title: "Rest Areas",
    tagline: "Quiet Spaces to Recharge",
    text: "Young bodies run out of battery without warning. Our classrooms include carpeted quiet corners with soft cushions where a tired child can nap or simply sit out the noise for a while. Rest here is treated as a need to be honoured, not a disruption to be managed.",
    tone: "secondary",
  },
  {
    icon: Droplets,
    title: "Health Policy",
    tagline: "Hygiene First, Always",
    text: "Infection control is a daily discipline at our campus, not a poster. Hot water, liquid soap, sanitisers, and paper towels are stocked and within children's reach all day; classrooms and play zones are disinfected daily with child-safe products; and every staff member maintains a current paediatric first-aid certification.",
    tone: "gold",
  },
  {
    icon: UserCheck,
    title: "Children Collection Policy",
    tagline: "Your Child's Safety, Our Priority",
    text: "Release of a child follows one unbreakable rule: only to a parent or an adult the parent has authorised in advance, and only after identity verification. There is no charm, familiarity, or urgency that overrides this. We also ask parents to be punctual at pickup — waiting past the crowd is genuinely distressing for a small child.",
    tone: "orange",
    size: "lg",
  },
  {
    icon: MessageCircleHeart,
    title: "Comments & Complaints",
    tagline: "We Are Always Listening",
    text: "Concerns should travel the shortest path first: your child's class teacher, who resolves most matters in a single honest conversation. Anything unresolved escalates to the Centre Head, with our written commitment to a full review and response within 5 working days. A raised concern is data we want, never a nuisance.",
    tone: "secondary",
  },
  {
    icon: Sparkles,
    title: "Behaviour Management",
    tagline: "Positive Guidance, Patient Support",
    text: "Biting, grabbing, meltdowns — these are developmental stages, not character flaws, and we treat them that way. Our educators redirect, model, and coach self-regulation; they never punish or shame. Where a pattern suggests a child needs specialist support, we raise it with parents early and honestly, with recommendations.",
    tone: "primary",
  },
];

export const POLICIES_GROUP_TWO = [
  {
    icon: Users,
    title: "Equal Opportunities",
    tagline: "Every Child Welcome",
    text: "Admission and daily treatment at Kayo carry no filter of religion, caste, language, gender, ability, or family background. Our staff are trained to celebrate difference actively — not merely tolerate it — so every child in our care experiences belonging as a fact, not an aspiration.",
    tone: "primary",
    size: "lg",
  },
  {
    icon: Apple,
    title: "Healthy Eating Policy",
    tagline: "Good Food, Good Habits",
    text: "Food habits formed at three tend to last until thirty, so we take the menu seriously: balanced, fresh, and planned for growing bodies, with processed snacks and sugary drinks kept off the table. We ask families to hold the same line in tiffin boxes — consistency between home and school is what makes the habit stick.",
    tone: "secondary",
  },
  {
    icon: Baby,
    title: "Toilet Training",
    tagline: "Supporting Independence with Patience",
    text: "Toilet independence arrives on the child's clock, not the calendar's. Our educators encourage without ever pressuring, celebrate progress quietly, and treat accidents as non-events. We stay in close sync with parents on what is happening at home, so the child experiences one consistent, unhurried approach everywhere.",
    tone: "gold",
  },
  {
    icon: CalendarX2,
    title: "Absence & Sickness",
    tagline: "Keeping Us Informed",
    text: "A quick message on the morning your child stays home — that is all we ask. It keeps our attendance accurate and lets teachers plan the day. After a longer absence, a short conversation with the Centre Head helps us plan a smooth re-entry, so returning feels like coming back, not starting over.",
    tone: "orange",
  },
  {
    icon: BandageIcon,
    title: "Accident & Injury",
    tagline: "Immediate Care, Clear Communication",
    text: "Active children collect the occasional scrape; what matters is the response. Every staff member is paediatric-first-aid trained and acts immediately. Every incident — however trivial — reaches the parent the same day through our communication system, or by phone if it warrants more, and a written report is filed and shared. Nothing is minimised, nothing is hidden.",
    tone: "secondary",
    size: "lg",
  },
];
